apiVersion: batch/v1
kind: Job
metadata:
  name: acs-policy-update
  namespace: rhacs-operator
spec:
  template:
    spec:
      serviceAccountName: central
      containers:
      - name: policy-update
        image: registry.access.redhat.com/ubi9/ubi-minimal:9.3    # Includes both jq + curl
        command: ["/bin/sh", "-c"]
        args:
          - |
            microdnf install -y jq curl
            CENTRAL_HOST=$(cat /creds/central_host)
            TOKEN=$(cat /creds/api_token)

            for f in /policies/*.json; do
              echo "Processing $f"
              id=$(jq -r '.id' "$f")
              if [ -n "$id" ] && [ "$id" != "null" ]; then
                echo "Updating policy ID: $id"
                curl -sk -X PUT \
                  -H "Authorization: Bearer $TOKEN" \
                  -H "Content-Type: application/json" \
                  --data-binary @"$f" \
                  "https://$CENTRAL_HOST/v1/policies/$id"
              else
                echo "No ID found in $f — skipping"
              fi
            done
        volumeMounts:
        - name: creds
          mountPath: /creds
          readOnly: true
        - name: policies
          mountPath: /policies
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: creds
        secret:
          secretName: acs-api-credentials
      - name: policies
        configMap:
          name: acs-policies

