apiVersion: batch/v1
kind: Job
metadata:
  name: acs-policy-import
  namespace: rhacs-operator
spec:
  template:
    spec:
      serviceAccountName: central   # Keep if you need, else can drop
      containers:
      - name: policy-import
        image: curlimages/curl:8.5.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            CENTRAL_HOST=$(cat /creds/central_host)
            TOKEN=$(cat /creds/api_token)

            for f in /policies/*.json; do
              echo "Importing $f"
              curl -sk -X POST \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                --data @"$f" \
                "https://$CENTRAL_HOST/v1/policies"
            done
        volumeMounts:
        - name: creds
          mountPath: /creds
          readOnly: true
        - name: policies
          mountPath: /policies
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: creds
        secret:
          secretName: acs-api-credentials   # must contain central_host and api_token keys
      - name: policies
        configMap:
          name: acs-policies                # must contain your policy JSONs

