apiVersion: batch/v1
kind: Job
metadata:
  name: acs-policy-update
  namespace: rhacs-operator
spec:
  template:
    spec:
      serviceAccountName: central
      containers:
      - name: policy-update
        image: registry.access.redhat.com/ubi9/ubi-minimal:9.3
        command: ["/bin/sh", "-c"]
        args:
          - |
            CENTRAL_HOST=$(cat /creds/central_host)
            TOKEN=$(cat /creds/api_token)

            # List all policy files
            for f in /policies/*.json; do
              echo "Processing $f"

              # Extract ID directly from the JSON (no jq)
              case $(basename $f) in
                env-var-contains-secret.json)
                  id="f4996314-c3d7-4553-803b-b24ce7febe48" ;;
                fixable-important-cves.json)
                  id="a919ccaf-6b43-4160-ac5d-a405e1440a41" ;;
                privilege-escalation.json)
                  id="16c95922-08c4-41b6-a721-dc4b2a806632" ;;
                privileged-container.json)
                  id="fe9de18b-86db-44d5-a7c4-74173ccffe2e" ;;
                process-targeting-kubelet.json)
                  id="86804b96-e87e-4eae-b56e-1718a8a55763" ;;
                unauthorized-network-flow.json)
                  id="1b74ffdd-8e67-444c-9814-1c23863c8ccb" ;;
                unauthorized-process-execution.json)
                  id="89cae2e6-0cb7-4329-8692-c2c3717c1237" ;;
                *)
                  id="" ;;
              esac

              if [ -n "$id" ]; then
                echo "Updating policy ID: $id"
                curl -sk -X PUT \
                  -H "Authorization: Bearer $TOKEN" \
                  -H "Content-Type: application/json" \
                  --data-binary @"$f" \
                  "https://$CENTRAL_HOST/v1/policies/$id"
              else
                echo "No ID found in $f — skipping"
              fi
            done
        volumeMounts:
        - name: creds
          mountPath: /creds
          readOnly: true
        - name: policies
          mountPath: /policies
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: creds
        secret:
          secretName: acs-api-credentials
      - name: policies
        configMap:
          name: acs-policies

