apiVersion: batch/v1
kind: Job
metadata:
  name: acs-policy-import
  namespace: rhacs-operator
spec:
  template:
    spec:
      serviceAccountName: central   # Ensure SA has minimal permissions (or remove if not needed)
      containers:
      - name: policy-import
        image: image: quay.io/stackrox/main:4.4.3
        command: ["/bin/sh", "-c"]
        args:
          - |
            CENTRAL_HOST=$(cat /creds/central_host)
            TOKEN=$(cat /creds/api_token)
            for f in /policies/*.json; do
              echo "Importing $f"
              roxctl central policy import \
                --insecure-skip-tls-verify \
                -e "$CENTRAL_HOST:443" \
                --token "$TOKEN" \
                --file "$f"
            done
            
        volumeMounts:
        - name: creds
          mountPath: /creds
          readOnly: true
        - name: policies
          mountPath: /policies
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: creds
        secret:
          secretName: acs-api-credentials
      - name: policies
        configMap:
          name: acs-policies
